require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/templates/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - config/initializers/*

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Description: 'Avoid chaining a method call on a do...end block.'
  StyleGuide: '#single-line-blocks'
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
  Exclude:
    - "config/**/*"

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitExpect:
  Description: Check that a consistent implict expectation style is used.
  Enabled: false
  EnforcedStyle: is_expected
  SupportedStyles:
    - is_expected
    - should

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - "config/**/*"

RSpec/ExampleLength:
  Max: 15

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false