default: &default
  bucket: qweqweqweqweqweqwe
  access_key_id: ASDADASDASDASDAS
  secret_access_key: ASDAsdAASsasaASASsasa

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
